---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Dezembro Solidário @ UMinho"
keywords:    "CeSIUM, jekyll, December, github, universidade do minho, departamento informatica"
description: "Dezembro Solidário é um projeto de cariz social que tem como objetivo trazer uma maior celebração da época natalícia à Universidade do Minho através de incentivos à solidariedade da comunidade académica."
source_link: "https://github.com/cesium/dezembro_solidario"
favicon:     "img/christmas-tree.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-67237593-6 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  white:        '#f0f0f0'
  grey :        '#696969'
  yellow:       '#fef99c'
  intro:        '#70161a'
  description:  '#8b161c'
  allmonth:     '#93281d'
  firstweek:    '#9b3f1f'
  secondweek:   '#9b511f'
  thirdweek:    '#96640e'
  fourthweek:   '#9c731a'
  contacts:     '#424242'

kramdown:
  auto_ids:  false

sass:
  sass_dir: stylesheets/_sass/
